/**
 * Anthropic Adapter
 *
 * Adapter for Claude models via the Anthropic API.
 * Used by KVASIR for deep reasoning.
 */

import { Injectable } from '@nestjs/common';
import { CouncilMember, createLogger } from '@yggdrasil/shared';
import { ILLMAdapter, CouncilMemberResponse, COUNCIL_SYSTEM_PROMPTS } from './llm.adapter.js';

const logger = createLogger('AnthropicAdapter', 'info');

interface AnthropicMessage {
  role: 'user' | 'assistant';
  content: string;
}

interface AnthropicResponse {
  id: string;
  type: 'message';
  role: 'assistant';
  content: Array<{ type: 'text'; text: string }>;
  model: string;
  stop_reason: string;
  usage: {
    input_tokens: number;
    output_tokens: number;
  };
}

@Injectable()
export class AnthropicAdapter implements ILLMAdapter {
  readonly member = CouncilMember.KVASIR;
  readonly modelId: string;
  private readonly apiKey: string | undefined;
  private readonly baseUrl = 'https://api.anthropic.com/v1';

  constructor() {
    this.apiKey = process.env['ANTHROPIC_API_KEY'];
    this.modelId = process.env['ANTHROPIC_MODEL'] ?? 'claude-3-5-sonnet-20241022';
  }

  isAvailable(): boolean {
    return !!this.apiKey;
  }

  async query(prompt: string): Promise<CouncilMemberResponse> {
    if (!this.isAvailable()) {
      logger.warn('Anthropic API key not configured, using placeholder');
      return this.placeholderResponse(prompt);
    }

    try {
      const messages: AnthropicMessage[] = [{ role: 'user', content: prompt }];

      const response = await fetch(`${this.baseUrl}/messages`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': this.apiKey!,
          'anthropic-version': '2023-06-01',
        },
        body: JSON.stringify({
          model: this.modelId,
          max_tokens: 2048,
          system: COUNCIL_SYSTEM_PROMPTS[this.member],
          messages,
        }),
      });

      if (!response.ok) {
        throw new Error(`Anthropic API error: ${response.status}`);
      }

      const data = (await response.json()) as AnthropicResponse;
      const content = data.content[0]?.text ?? '';

      logger.info('KVASIR (Claude) response received', {
        model: data.model,
        inputTokens: data.usage.input_tokens,
        outputTokens: data.usage.output_tokens,
      });

      return {
        content,
        confidence: this.estimateConfidence(content),
        reasoning: 'Response generated by Claude via Anthropic API',
        model: data.model,
      };
    } catch (error) {
      logger.error('Anthropic API call failed', error as Error);
      return this.placeholderResponse(prompt);
    }
  }

  private placeholderResponse(prompt: string): CouncilMemberResponse {
    return {
      content: `[KVASIR/Claude placeholder] Query: "${prompt.slice(0, 50)}..."`,
      confidence: 50,
      reasoning: 'Placeholder - Anthropic API not available',
    };
  }

  private estimateConfidence(content: string): number {
    // Simple heuristic - real implementation would be more sophisticated
    const uncertainWords = ['might', 'maybe', 'possibly', 'uncertain', 'unclear'];
    const confidentWords = ['definitely', 'certainly', 'clearly', 'verified'];

    const lowerContent = content.toLowerCase();
    let confidence = 70;

    for (const word of uncertainWords) {
      if (lowerContent.includes(word)) confidence -= 5;
    }
    for (const word of confidentWords) {
      if (lowerContent.includes(word)) confidence += 5;
    }

    return Math.max(30, Math.min(95, confidence));
  }
}
