/**
 * OpenAI Compatible Adapter
 *
 * Adapter for OpenAI API and compatible providers (DeepSeek, Together, etc.)
 * Used by NORNES (DeepSeek) and BRAGI (GPT/Grok).
 */

import { Injectable } from '@nestjs/common';
import { CouncilMember, createLogger } from '@yggdrasil/shared';
import { ILLMAdapter, CouncilMemberResponse, COUNCIL_SYSTEM_PROMPTS } from './llm.adapter.js';

const logger = createLogger('OpenAIAdapter', 'info');

interface OpenAIMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

interface OpenAIResponse {
  id: string;
  choices: Array<{
    message: { role: string; content: string };
    finish_reason: string;
  }>;
  model: string;
  usage: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
}

export interface OpenAIAdapterConfig {
  member: CouncilMember;
  apiKeyEnvVar: string;
  baseUrl: string;
  defaultModel: string;
  modelEnvVar: string;
}

@Injectable()
export class OpenAICompatibleAdapter implements ILLMAdapter {
  readonly member: CouncilMember;
  readonly modelId: string;
  private readonly apiKey: string | undefined;
  private readonly baseUrl: string;

  constructor(config: OpenAIAdapterConfig) {
    this.member = config.member;
    this.apiKey = process.env[config.apiKeyEnvVar];
    this.baseUrl = config.baseUrl;
    this.modelId = process.env[config.modelEnvVar] ?? config.defaultModel;
  }

  isAvailable(): boolean {
    return !!this.apiKey;
  }

  async query(prompt: string): Promise<CouncilMemberResponse> {
    if (!this.isAvailable()) {
      logger.warn(`${this.member} API key not configured, using placeholder`);
      return this.placeholderResponse(prompt);
    }

    try {
      const messages: OpenAIMessage[] = [
        { role: 'system', content: COUNCIL_SYSTEM_PROMPTS[this.member] },
        { role: 'user', content: prompt },
      ];

      const response = await fetch(`${this.baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${this.apiKey}`,
        },
        body: JSON.stringify({
          model: this.modelId,
          max_tokens: 2048,
          messages,
        }),
      });

      if (!response.ok) {
        throw new Error(`API error: ${response.status}`);
      }

      const data = (await response.json()) as OpenAIResponse;
      const content = data.choices[0]?.message.content ?? '';

      logger.info(`${this.member} response received`, {
        model: data.model,
        promptTokens: data.usage.prompt_tokens,
        completionTokens: data.usage.completion_tokens,
      });

      return {
        content,
        confidence: this.estimateConfidence(content),
        reasoning: `Response generated by ${data.model}`,
        model: data.model,
      };
    } catch (error) {
      logger.error(`${this.member} API call failed`, error as Error);
      return this.placeholderResponse(prompt);
    }
  }

  private placeholderResponse(prompt: string): CouncilMemberResponse {
    return {
      content: `[${this.member} placeholder] Query: "${prompt.slice(0, 50)}..."`,
      confidence: 50,
      reasoning: `Placeholder - ${this.member} API not available`,
    };
  }

  private estimateConfidence(content: string): number {
    const uncertainWords = ['might', 'maybe', 'possibly', 'uncertain', 'unclear'];
    const confidentWords = ['definitely', 'certainly', 'clearly', 'verified'];

    const lowerContent = content.toLowerCase();
    let confidence = 70;

    for (const word of uncertainWords) {
      if (lowerContent.includes(word)) confidence -= 5;
    }
    for (const word of confidentWords) {
      if (lowerContent.includes(word)) confidence += 5;
    }

    return Math.max(30, Math.min(95, confidence));
  }
}

/**
 * Factory functions for specific providers
 */

@Injectable()
export class NornesAdapter extends OpenAICompatibleAdapter {
  constructor() {
    super({
      member: CouncilMember.NORNES,
      apiKeyEnvVar: 'DEEPSEEK_API_KEY',
      baseUrl: 'https://api.deepseek.com/v1',
      defaultModel: 'deepseek-chat',
      modelEnvVar: 'DEEPSEEK_MODEL',
    });
  }
}

@Injectable()
export class BragiAdapter extends OpenAICompatibleAdapter {
  constructor() {
    super({
      member: CouncilMember.BRAGI,
      apiKeyEnvVar: 'OPENAI_API_KEY',
      baseUrl: 'https://api.openai.com/v1',
      defaultModel: 'gpt-4-turbo-preview',
      modelEnvVar: 'OPENAI_MODEL',
    });
  }
}
